service:
  name: ${self:custom.name}

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.name}.${self:provider.region}.deploy
  memorySize: 2048
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "KMS:Decrypt"
      Resource: ${self:custom.kmsSecrets.keyArn}
  environment:
    ASANA_PROJECT_ID: ${self:custom.config.asana.project_id}
    ASANA_TOKEN: ${self:custom.kmsSecrets.secrets.ASANA_TOKEN}
    JIRA_HOST: ${self:custom.config.jira.host}
    JIRA_USERNAME: ${self:custom.config.jira.username}
    JIRA_PASSWORD: ${self:custom.kmsSecrets.secrets.JIRA_PASSWORD}
    JIRA_PROJECT_ID: ${self:custom.config.jira.project_id}
    JIRA_STORY_ISSUE_ID: ${self:custom.config.jira.story_issue_id}
    JIRA_BUG_ISSUE_ID: ${self:custom.config.jira.bug_issue_id}
    JIRA_ASANA_FIELD_ID: ${self:custom.config.jira.asana_field_id}

custom:
  name: asana-jira-syncer
  serverless-kms-secrets:
    secretsFile: config/secure.yml
  kmsSecrets: ${file(./config/secure.yml)}
  config: ${file(./config/sls-config.yml)}

plugins:
  - serverless-offline
  - serverless-kms-secrets

functions:
  asanaIncommingWebhook:
    handler: handler.asanaIncommingWebhook
    events:
      - http:
          path: '/asana'
          method: 'post'
          private: false
  jiraIncommingWebhook:
    handler: handler.jiraIncommingWebhook
    events:
      - http:
          path: '/jira'
          method: 'post'
          private: false
